version: 2.1
orbs:
  github-cli: circleci/github-cli@2.3.0
  android: circleci/android@2.5.0
jobs:
  build-release:
    executor:
      name: android/android-docker
      tag: default
    steps:
      - run: git clone git@github.com:qufighter/SDL_ColorPick.git
      - run: cd SDL_ColorPick/android-project
      - run:
          name: Create builds
          command: ./buildAllRelease.sh
      - store_artifacts:
          path: app/build/outputs/
workflows:
  build:
    jobs:
      - build-release
